name: Telegram Message Fetcher

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:  # 允许手动触发

env:
  PYTHON_VERSION: '3.10'
  SITE_TITLE: 'Telegram 群聊消息存档'
  ITEMS_PER_PAGE: 50
  TIMEZONE: 'Asia/Shanghai'

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv pytz

      - name: Create data directory
        run: mkdir -p data

      - name: Fetch Telegram messages
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python scripts/fetch_messages.py

      - name: Generate HTML page
        run: |
          python scripts/generate_page.py

      - name: Setup Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check for changes
        id: check_changes
        run: |
          git add -A
          if git diff-index --quiet HEAD --; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes to commit"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git commit -m "Auto-update: Fetch new Telegram messages [skip ci]"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          allow_empty_commit: false
          keep_files: true
          enable_jekyll: false
