name: Telegram Message Fetcher with GitHub API

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:  # 允许手动触发

env:
  PYTHON_VERSION: '3.10'
  SITE_TITLE: 'Telegram 群聊消息存档'
  ITEMS_PER_PAGE: 50
  TIMEZONE: 'Asia/Shanghai'
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Create data directory
        run: mkdir -p data

      - name: Fetch Telegram messages
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python scripts/fetch_messages.py

      - name: Generate HTML page
        run: |
          python scripts/generate_page.py

      - name: Update files via GitHub API
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REPO_OWNER: ${{ env.REPO_OWNER }}
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          python scripts/update_via_api.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./
          allow_empty_commit: false
          keep_files: true
          enable_jekyll: false
